# -*- coding: utf-8 -*-
"""anagram.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1slVZeShG7o0r_yWwrKqUrW48qilL66LB
"""

def is_anagram(s,t):
  letter = {}
  if len(s) != len(t):
    return False

  for val in s:
    if val in letter:
        letter[val]+=1
    else:letter[val]=1

  for val in t:
    if val in letter:
      if letter[val] > 0:
         letter[val]-=1
      else: return False

    else: return False

  return True

s = "anagram"
t = "nagaram"
print(is_anagram(s,t))

# More efficient version:

def is_anagram(s, t):
    if len(s) != len(t):
        return False

    letter = {}

    for val in s:
        letter[val] = letter.get(val, 0) + 1

    for val in t:
        if letter.get(val, 0) == 0:
            return False
        letter[val] -= 1

    return True

print(is_anagram(s,t))

# Time complexity: O(n)
# space complexity: O(n)

# Another way to do:

def is_anagram(s,t):
  if len(s) != len(t):
    return False

  count = [0] * 26

  for i in range(len(s)):
    count[ord(s[i])-ord('a')] += 1
    count[ord(s[i])-ord('a')] -= 1

  return all(c == 0 for c in count)

print(is_anagram(s,t))

