# -*- coding: utf-8 -*-
"""contains_duplicate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhyxoRpUbyq7-Gjx0BimskNgKgtfOjqI
"""

def contain_duplicate(nums):
        letter = {}

        for i in range(len(nums)):
            if nums[i] in letter:
                return True
            letter[nums[i]] = i

        return False

print(contain_duplicate([1,2,3,3]))

def contain_duplicate(nums):
        letter = set()

        for i in range(len(nums)):
            if nums[i] in letter:
                return True
            letter.add(nums[i])

        return False

print(contain_duplicate([1,2,3,4]))

