# -*- coding: utf-8 -*-
"""group_anagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oXcgzAxDYAU7qB33E-LQSZLEGrVQj_r
"""

def group_anagram(strs):
  group = {}

  for val in strs:
    count = [0]*26

    for ch in val:
      count[ord(ch) - ord('a')] += 1

    # Convert the mutable list 'count' to an immutable tuple to use as a dictionary key
    # and initialize an empty list if the key doesn't exist before appending.
    group.setdefault(tuple(count), []).append(val)

    # count = tuple(count)
    # if count in group:
    #      group[count].append(val)

    # else: group[count] = [val]

  # use values() for getting all values in dict.
  return list(group.values())

input = ["eat","tea","tan","ate","nat","bat"]
print(group_anagram(input)) # Changed 'input' to 'Input'

