# -*- coding: utf-8 -*-
"""longest_substr_with_k_distinct_char.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfZl2D1BRhnCgDRvxAWGZ1s0e2W9B_ga
"""

def longest_substr_with_k_distinct_char(s,k):

  if not k:
    return 0

  left = 0
  required = k
  have = {}
  char = 0
  max_len = float('-inf')

  for right in range(len(s)):
    c = s[right]
    have[c] = have.get(c,0)+1

    if have[c] == 1: char+=1

    if char == required and right - left + 1 > max_len:
        max_len = right - left + 1

    while char > required:
      left_char = s[left]
      if have[left_char] == 1:
        char -= 1
      have[left_char] -= 1
      left+=1

  return max_len

s = "aa"
k = 0
print(longest_substr_with_k_distinct_char(s,k))

## More refined version

def longest_substr_with_k_distinct_char(s, k):
    if k == 0:
        return 0

    left = 0
    have = {}
    max_len = 0

    for right in range(len(s)):
        c = s[right]
        have[c] = have.get(c, 0) + 1

        # Shrink window if distinct chars > k
        while len(have) > k:
            left_char = s[left]
            have[left_char] -= 1
            if have[left_char] == 0:
                del have[left_char]
            left += 1

        # Update max length (VALID window)
        max_len = max(max_len, right - left + 1)

    return max_len