# -*- coding: utf-8 -*-
"""longest_str_with_distinct_char.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IktRAQZYW9FOowELWayGPngFrwI6h53E
"""

def longest_str(s):

  seen = set()
  left = 0
  max_len = 1

  for right in range(len(s)):
    while s[right] in seen:
      seen.remove(s[left])
      left+=1
    seen.add(s[right])
    max_len = max(max_len, right-left+1)
    right+=1

  return max_len

s = "abcabcbbba"
print(longest_str(s))

