# -*- coding: utf-8 -*-
"""min_window_substr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160ojxtKrTPcG2217J079MF8s2__5eV-e
"""

def min_window(s: str, t: str) -> str:
    if not s or not t:
        return ""

    need = {}
    for ch in t:
        need[ch] = need.get(ch, 0) + 1

    have = {}
    required = len(need)
    formed = 0

    left = 0
    min_len = float('inf')
    res = (0, 0)

    for right in range(len(s)):
        c = s[right]
        have[c] = have.get(c, 0) + 1

        if c in need and have[c] == need[c]:
            formed += 1

        # Try shrinking the window
        while formed == required:
            if (right - left + 1) < min_len:
                min_len = right - left + 1
                res = (left, right)

            left_char = s[left]
            have[left_char] -= 1

            if left_char in need and have[left_char] < need[left_char]:
                formed -= 1

            left += 1

    l, r = res
    return s[l:r+1] if min_len != float('inf') else ""

s = "ADOBECODEBANC"
t = "ABC"
print(min_window(s,t))

