# -*- coding: utf-8 -*-
"""product_of_array_except_self.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyltrM2bLMQPN1ORepUqftuo9vIpfJAF
"""

def product_of_arr_except_itself(nums):
    left = 1
    right = 1
    length = len(nums)
    ans = [1]*length

    for i in range(length):
      ans[i] *= left
      left *= nums[i]

    for i in range(length-1,-1,-1):
      ans[i] *= right
      right *= nums[i]

    return ans

nums = [1,2,3,4]
print(product_of_arr_except_itself(nums))

