# -*- coding: utf-8 -*-
"""two_sum.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wz8EbxwcyVUPCte2bG6Ak8EfgeQQJZnk
"""

def two_sum(target,nums):
  map = {}

  for i in range(len(nums)):
    val = target - nums[i]
    if nums[i] in map:
      print([map[nums[i]],i])
    map[val] = i

target = 9
nums = [2,7,11,15]
two_sum(target,nums)

